# Generated by Django 5.2 on 2025-05-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('hanja_name', models.CharField(max_length=4)),
                ('birth_date', models.CharField(blank=True, max_length=20, null=True)),
                ('party', models.CharField(max_length=30)),
                ('district', models.CharField(max_length=30)),
                ('elected_type', models.CharField(max_length=20)),
                ('reelection', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=3)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=30)),
                ('main_committee', models.CharField(max_length=30)),
                ('member_code', models.CharField(max_length=30)),
                ('election_unit', models.CharField(max_length=50)),
            ],
        ),
    ]
