# Generated by Django 5.2 on 2025-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='MemberInfo',
        ),
        migrations.CreateModel(
            name='MemberImageInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(max_length=300)),
                ('member', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='DashBoard.memberinfo')),
            ],
        ),
    ]
