# Generated by Django 5.2 on 2025-05-08 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0002_rename_member_memberinfo_memberimageinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberimageinfo',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='memberimageinfo', to='DashBoard.memberinfo'),
        ),
    ]
