# Generated by Django 5.2 on 2025-05-11 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0003_alter_memberimageinfo_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='pass_rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='passed_bills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='memberinfo',
            name='total_bills',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='memberimageinfo',
            name='member',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='MemberImageInfo', to='DashBoard.memberinfo'),
        ),
    ]
