# Generated by Django 5.2 on 2025-05-12 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0005_alter_memberinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='birth_date',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='district',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='elected_type',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='election_unit',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='email',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='gender',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='hanja_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='main_committee',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='party',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='phone',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='position',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='memberinfo',
            name='reelection',
            field=models.CharField(max_length=200),
        ),
    ]
