# Generated by Django 5.2 on 2025-05-12 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0006_alter_memberinfo_birth_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberinfo',
            name='member_code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
