# Generated by Django 5.2 on 2025-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DashBoard', '0007_alter_memberinfo_member_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberinfo',
            name='attendance_rate',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
